- name: update apt cache
  apt:
    update_cache: yes


- name: install postgresql
  package:
    name:
      - postgresql
      - python3-psycopg2
      - acl # for become_user to work with unprivileged user
    state: present


- name: Start and enable services
  service: "name={{ item }} state=started enabled=yes"
  with_items:
    - postgresql