- name: update apt cache
  apt:
    update_cache: yes


- name: install postgresql
  apt:
    name:
      - postgresql
      - python3-psycopg2
      - acl # for become_user to work with unprivileged user
    state: present